services:
  - type: web
    name: crypto-bot-debug-full
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: your_bot_token_here
